### ISSUE TITLE
error when trying to train my CNN

### ISSUE THREAD

**Issue by emoebel** [ELEKTRONN/ELEKTRONN#1]
Hi,
I just performed the MNIST tutorial successfully, and for practice am now trying to train my own 3D CNN to classify synthetic images into 2 classes (presence/absence of an ellipse, 1000 images/class). But when executing elektronn-train with my config file, I get the error :

```
...
GLOBAL
Computational Cost: 136.5 Mega Ops
Total Count of trainable Parameters: 916834
Building Computational Graph took 0.077 s
Compiling output functions for nll target:
    using no class_weights
    using no example_weights
    using no lazy_labels
    label propagation inactive

 Compiling done  - in 4.285 s!
------------------------------------------------------------
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elektronn/training/trainer.py", line 172, in run
    batch = data.getbatch(**self.get_batch_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elektronn/training/CNNData.py", line 623, in get batch
    d, _ = _randomFlip(d, d, self.rng, self.aniso, self.upright_x)  # lazy hack to exclude labels from transform
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elektronn/training/CNNData.py", line 115, in _randomFlip
    l = np.transpose(l, T)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 551, in transpose
    return transpose(axes)
ValueError: axes don't match array
```

I suppose there is something wrong with the file containing the labels, here is how my data and label files are organized:

```
dataFile.h5
|-dataset1 = image1
|-dataset2 = image2
:
labelFile.h5
|-dataset1 = label1
|-dataset2 = label2
:
```

Also, in attachment you can find my config file. Any idea what I'm doing wrong here?
[CNN_for_3Dphantom_config.py.zip](https://github.com/ELEKTRONN/ELEKTRONN/files/153331/CNN_for_3Dphantom_config.py.zip)

**Comment by xeray** [comment]
Hi Lazyleaf,

this error arises from the data augmentation by flipping/transposing the array axes. There was a bug for the case that the labels were scalar and the image 3d. I think I just fixed it. If you can update ELEKTRONN directly from github you can test if it works now. Otherwise I'll have the pipy and conda packages updated within a day.

If it still doesn't work, please send me the full printed output and the exact shapes of arrays that you put into the h5-files.

Cheers
Marius

**Comment by emoebel** [comment]
My data and label shapes : data.shape=(32, 1, 32, 32), label.shape=(1,)
Attached is my complete output.

Indeed, when I turn off the data augmentation, training starts without crashing. I however observe 2 odd behaviors  :

```
------------------------------------------------------------
Compiling SGD
 Compiling done  - in 6.701 s!
00000 NLLm=0.655, train=100.00%, valid=60.000%, prev=100.0, NLLdiff=-8.7e-01, LR=0.00099, 0.3 it/s, t=7s
00500 NLLm=0.061, train=00.00%, valid=0.000%, prev=100.0, NLLdiff=-3.6e-07, LR=0.00099, 12.3 it/s, t=49s
01000 NLLm=0.005, train=00.00%, valid=0.000%, prev=00.0, NLLdiff=+0.0e+00, LR=0.00099, 11.3 it/s, t=91s
01500 NLLm=0.000, train=00.00%, valid=0.000%, prev=100.0, NLLdiff=-1.2e-07, LR=0.00099, 12.2 it/s, t=132s
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py:3045: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
02000 NLLm=0.000, train=00.00%, valid=0.000%, prev=00.0, NLLdiff=+0.0e+00, LR=0.00098, 11.7 it/s, t=174s
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py:3045: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
02500 NLLm=0.000, train=00.00%, valid=0.000%, prev=100.0, NLLdiff=+0.0e+00, LR=0.00098, 12.1 it/s, t=217s
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py:3045: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
...
```

[1] The train and validation errors immediately tend to 0, I would like to believe that my network is super effective, but I suspect this is rather some disfunction in my setup 
[2] After a moment I get a warning between the training steps, but since it comes from matplotlib, I assume it is not important? 
[files.zip](https://github.com/ELEKTRONN/ELEKTRONN/files/155037/files.zip)

**Comment by xeray** [comment]
Hi Lazyleaf,

the warning is directly related to the first problem because the y-axes of the plots are scaled between 0 and the maximal error - which is apparently 0 in your case - there is a warning if the two values coincide.

I don't know what your training task is in particular. But you've written that you want to predict the presence/absence of an ellipse. Do your pictures contain anything else than an ellipse? In particular do the negative examples contain any content at all? If not, your task would be highly trivial and could be solved by something as simple as a threshold on the average intensity... (which would also be the case if you add something like salt and pepper noise to all pictures: the ellipse pictures would still have higher average intensity).

We've just uploaded new packages to pypi and conda (the AUR package is still in work). Let me know if that fixed your initial problem.

**Comment by emoebel** [comment]
Hi,

I reinstalled elektronn via pip, and now training runs smoothly with flip_data = True !

And also you were right about the triviality of the task : instead of presence/absence of an ellipse, I tried a new task with class1=ellipse,class2:cuboid. And indeed, the errors now have much more difficulties to tend to 0 : the errors plateau from beginning to the end (21k iterations). But I still have a lot to learn about CNN optimization!

Thanks for your reactivity and your advice!

**Comment by xeray** [comment]
Ok, I'm happy that it works now.

Yeah, using CNNs can be tricky. You have to think about a good architecture, the right optimisation parameters and (quite importantly) a good "formulation" of the task that you want to achieve. I consider this issue closed now. If you get stuck with the optimisation, you can write an E-Mail to me.
