### ISSUE TITLE
error while trying to make a prediction

### ISSUE THREAD

**Issue by emoebel** [ELEKTRONN/ELEKTRONN#2]
Hi, here I am again.
I trained a network and managed to get the errors to tend toward zero. I now would like to use this network to predict the class of an image. But when I call predictDense() I get following error:

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2493, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 288, in execfile
    builtin_mod.execfile(filename, *where)
  File "/Users/emoebel/code/python/CNN_training/3D/attempt2/prediction_script.py", line 22, in <module>
    prediction = cnn.predictDense(raw_img, show_progress=True, offset=None, as_uint8=False, pad_raw=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elektronn/net/convnet.py", line 1062, in predictDense
    tile_sh = np.add(ps, strides) - 1  # zxy
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

(complete output is attached)
[predict_script_output.txt](https://github.com/ELEKTRONN/ELEKTRONN/files/158944/predict_script_output.txt)

Here is what I do :

```
from elektronn.training.predictor import create_predncnn
from elektronn.net.convnet import MixedConvNN
import h5py
import numpy as np

# generate the cnn:
config_file = "/my-path/CNN_for_3Dphantom_config.py"
n_ch  = 1
n_lab = 2
param_file  = "/my-path/Debug/Debug-LAST.param"

cnn = create_predncnn(config_file, n_ch, n_lab, gpu=None, override_MFP_to_active=False, imposed_input_size=None, param_file=param_file)

# load the data:
test_data = "/my-data-path/phantom_dataset_classes2_size32_test.hdf5"
h5data = h5py.File(test_data, 'r')
raw_img = h5data['dataset1'][:]  # shape is (32,32,32), type is float64
raw_img = raw_img[None,:]  # add extra dim because predict method expects (ch, x, y, z)

# make prediction:
prediction = cnn.predictDense(raw_img, show_progress=True, offset=None, as_uint8=False, pad_raw=False)
```

Any advice?

**Comment by xeray** [comment]
Hi Lazyleaf,

your code looks sound except for one little thing: use `cnn.class_probabilities(data)` instead of `predictDense` - the latter is intended for "img-img" traininig where the target is not scalar but also image like (like the example image on the ELEKTRONN main page).
If you use `class_probabilities` you must pass the input data in the shape `(batch_size, z, channel, x, y)` which is in your case `(1, 32, 1, 32, 32)` as you can see from the output  in line 16.
What you get in return is a matrix of shape `(batch_size, n_lab)` with the corresponding probabilities, to assign a class you can use `np.argmax(prob, axis=1)` or use a tuned threshold.

Side Remark: if you have enough spare RAM on you GPU you can also batch-process the predictions, which might be a bit faster. To do so, create a new fork of the configuration file and use a bigger batch size there, then stack your data along the first `batch_size` axis. 

Cheers
Marius

**Comment by emoebel** [comment]
Hi Marius,

I indeed used the wrong method, I should have read the example better!
Thanks for your tips,

lazyleaf

**Comment by xeray** [comment]
No Problem,
the next release will have a specific error message for this.
