### ISSUE TITLE
error when using class_weights

### ISSUE THREAD

**Issue by emoebel** [ELEKTRONN/ELEKTRONN#4]
Hi there,

I think I may have found a little bug : 
I have a working config file (n_lab=2). But as soon as I set class_weights:
`class_weights = [0.1, 0.99]`
I get the error:

```
.
.
.
Compiling done  - in 1.856 s!
------------------------------------------------------------
------------------------------------------------------------
Traceback (most recent call last):
  File "/fs/pool/pool-bmapps/hpcl5/app/soft/PYTHON/2.7.9/lib/python2.7/site-packages/elektronn/training/trainer.py", line 175, in run
    batch = batch + (config.class_weights, )
TypeError: can only concatenate list (not "tuple") to list
```

I'm not a python crack, but if batch is a list this syntax can indeed not work

Best,
lazyleaf

**Comment by xeray** [comment]
Hi Lazyleaf,

you're absolutely right, thanks for spotting it. This bug never showed up before because I always used background processes for batch generation: https://github.com/ELEKTRONN/ELEKTRONN/blob/master/elektronn/training/trainer.py#L170 makes the return a tuple and so the actual mistake was shadowed...
